<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cancel</name>
   <tag></tag>
   <elementGuidId>3709627d-feff-4fc4-94e3-3c364639d204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/app-activity-add/div/div[2]/div[3]/ngx-material-timepicker/div[2]/div/div/div[2]/div/ngx-material-timepicker-button/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/app-activity-add[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;body-container&quot;]/div[@class=&quot;time-container flex-cross-center&quot;]/ngx-material-timepicker[@class=&quot;ng-tns-c10-6&quot;]/div[@class=&quot;timepicker-overlay ng-tns-c10-6 ng-star-inserted&quot;]/div[@class=&quot;timepicker ng-trigger ng-trigger-timepicker&quot;]/div[@class=&quot;timepicker__main-content&quot;]/div[@class=&quot;timepicker__actions&quot;]/div[@class=&quot;ng-tns-c10-6&quot;]/ngx-material-timepicker-button[@class=&quot;ng-tns-c10-6 ng-star-inserted&quot;]/button[@class=&quot;timepicker-button&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-activity-add/div/div[2]/div[3]/ngx-material-timepicker/div[2]/div/div/div[2]/div/ngx-material-timepicker-button/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[1]/following::span[65]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//ngx-material-timepicker-button/button/span</value>
   </webElementXpaths>
</WebElementEntity>
