<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>67a25b14-dda3-4c41-93f3-8d7f480d972d</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 1000 1000</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;outlet-container&quot;]/app-patient-list[@class=&quot;ng-tns-c1-0 ng-star-inserted&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;body-container flex-main-center&quot;]/div[@class=&quot;body-wrapper&quot;]/div[@class=&quot;list-container&quot;]/div[@class=&quot;activity-list-wrapper&quot;]/div[@class=&quot;activity-graph-body flex-main-center ng-tns-c1-0 ng-star-inserted&quot;]/div[@class=&quot;graph-container&quot;]/plotly-plot[@class=&quot;ng-tns-c1-0&quot;]/div[@class=&quot;js-plotly-plot&quot;]/div[@class=&quot;plot-container plotly&quot;]/div[@class=&quot;svg-container&quot;]/div[@class=&quot;modebar modebar--hover&quot;]/div[@class=&quot;modebar-group&quot;]/a[@class=&quot;modebar-btn&quot;]/svg[1]</value>
   </webElementProperties>
</WebElementEntity>
